# Generated by Django 2.2 on 2020-03-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('secret', models.CharField(blank=True, max_length=20, null=True)),
                ('server', models.CharField(blank=True, max_length=20, null=True)),
                ('farm', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('ispublic', models.IntegerField(blank=True, null=True)),
                ('isfriend', models.IntegerField(blank=True, null=True)),
                ('isfamily', models.IntegerField(blank=True, null=True)),
                ('ownername', models.CharField(blank=True, max_length=60, null=True)),
                ('dateadded', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Group')),
            ],
        ),
    ]
